id: c6af30b95b3446b099e42952feae886c
initial_creation_type: ocr
source_metadata:
  volumes:
    d657187269c24529a774d39d4e635faa:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་ཐམས་ཅད་ཀྱི་དམ་ཚིག་བསྲུང་བའི་སྒྲུབ་ཐབས།
      total_pages: 1044
      volume_number: 38
